# Package DVB-S2 Receiver IP core

create_project dvbs2rx . -force
add_files dvbs2rx.v
set_property top top [current_fileset]
load_features ipservices
ipx::package_project -import_files -root_dir . -vendor maia-sdr.org -library user -taxonomy /Maia-SDR -force
set_property name dvbs2rx [ipx::current_core]
set_property library user [ipx::current_core]
set_property display_name {DVB-S2 Receiver} [ipx::current_core]
set_property description {DVB-S2 receiver: RRC filter, Costas+M&M sync, SOF correlator, decision-directed PLL, PLS decoder, LDPC soft bits, column deinterleaver, AXI-Stream packet output} [ipx::current_core]
set_property vendor_display_name {Maia SDR} [ipx::current_core]
set_property company_url {https://maia-sdr.org} [ipx::current_core]
set_property version $::env(IP_CORE_VERSION) [ipx::current_core]

# ── Clock interface (sync domain → 'clk' port generated by Amaranth) ─────────
ipx::add_bus_interface sync_clk [ipx::current_core]
set_property abstraction_type_vlnv xilinx.com:signal:clock_rtl:1.0 \
    [ipx::get_bus_interfaces sync_clk -of_objects [ipx::current_core]]
set_property bus_type_vlnv xilinx.com:signal:clock:1.0 \
    [ipx::get_bus_interfaces sync_clk -of_objects [ipx::current_core]]
ipx::add_bus_parameter FREQ_HZ \
    [ipx::get_bus_interfaces sync_clk -of_objects [ipx::current_core]]
ipx::add_port_map CLK \
    [ipx::get_bus_interfaces sync_clk -of_objects [ipx::current_core]]
set_property physical_name clk \
    [ipx::get_port_maps CLK \
         -of_objects [ipx::get_bus_interfaces sync_clk -of_objects [ipx::current_core]]]

# ── Reset interface (active-high 'rst' port generated by Amaranth) ────────────
ipx::add_bus_parameter POLARITY \
    [ipx::get_bus_interfaces rst -of_objects [ipx::current_core]]
set_property value ACTIVE_HIGH \
    [ipx::get_bus_parameters POLARITY \
         -of_objects [ipx::get_bus_interfaces rst -of_objects [ipx::current_core]]]

# Associate reset with clock
ipx::associate_bus_interfaces -busif rst -clock sync_clk [ipx::current_core]

# ── AXI4-Stream master interface (LLR packets → ARM) ─────────────────────────
# Vivado auto-detects m_tdata/m_tvalid/m_tready/m_tlast as AXI4-Stream 'm'.
# We just set the clock association.
ipx::associate_bus_interfaces -busif m -clock sync_clk [ipx::current_core]

# ── AXI4-Lite slave interface (config/status registers) ──────────────────────
# Vivado auto-detects s_axi_lite_* ports as AXI4-Lite 's_axi_lite'.
# We just set the clock association and address space.
ipx::associate_bus_interfaces -busif s_axi_lite -clock sync_clk [ipx::current_core]

# Address space: 2 registers × 4 bytes = 8 bytes → range 0x8, width 3 bits
ipx::add_address_space s_axi_lite [ipx::current_core]
set_property master_address_space_ref s_axi_lite \
    [ipx::get_bus_interfaces s_axi_lite -of_objects [ipx::current_core]]
set_property range 8 \
    [ipx::get_address_spaces s_axi_lite -of_objects [ipx::current_core]]
set_property width 3 \
    [ipx::get_address_spaces s_axi_lite -of_objects [ipx::current_core]]

ipx::create_xgui_files [ipx::current_core]
ipx::save_core [ipx::current_core]
