create_bd_port -dir O pad_4
create_bd_port -dir O pad_6
create_bd_port -dir O pad_8
create_bd_port -dir O pad_10
create_bd_port -dir O pad_12
create_bd_port -dir O pad_14
create_bd_port -dir O pad_16_tx
create_bd_port -dir I pad_18_rx
create_bd_port -dir I ad936x_sync
